name: CI App Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  full-pipeline:
    uses: teranjoan/GithubActions-cicd/.github/workflows/full-pipeline.yml@master
    secrets: inherit
    with:
      environment: "dev"  # o "prd", "stg", "tst"