name: CI App Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  full-pipeline:
    uses: teranjoan/GithubActions/.github/workflows/full-pipeline.yml@master
    secrets:
      dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
      # Para testing puedes usar valores hardcodeados:
      # dockerhub_user: "cuamonga" 
      # dockerhub_password: "password"