name: CI App Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  full-pipeline:
    uses: ./.github/workflows/full-pipeline.yml
    secrets:
      # dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
      # dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
      dockerhub_user: "cuamonga"
      dockerhub_password: "password"
